global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'resource-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-service:8030']

  - job_name: 'storage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['storage-service:8034']

  - job_name: 'song-service-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['song-service-1:8031']

  - job_name: 'song-service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['song-service-2:8031']

  - job_name: 'resource-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-processor:8036']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8035']

  - job_name: 'eureka-registry'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-discovery-service:8032']